project:
  type: website
  resources: 
    - assets/

website:
  title: "gnczi theorycrafts"
  favicon: /assets/foxi.jpeg
  navbar:
    logo: /assets/foxi2.png
    left:
      - href: index.qmd
        text: Home
      - href: ttc.qmd
        text: The Tastetime Continuum
      - href: about.qmd
        text: About


format:
  html:
    image: /assets/foxi.jpeg
    code-fold: true
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    layout:
      xaxis:
        font:
          weight: bold