project:
  type: website

website:
  title: "quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: prices2.qmd
        text: The Tastetime continuum
      - href: about.qmd
        text: About


format:
  html:
    code-fold: true
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true
    layout:
      xaxis:
        font:
          weight: bold